library ieee;
use ieee.std_logic_1164.all;

-- CRC-32 generator with 2-bit (dibit) parallel input.
-- Polynomial : 0xEDB88320 (right-shift / little-endian)
-- Reset value: 0xFFFFFFFF
-- crc_out    : inverted combinatorial next-state (final XOR applied)
-- Source equations generated by https://bues.ch/h/crcgen
entity crc_32 is
    port (
        clk     : in  std_logic;
        reset_n : in  std_logic;                      
        data_in : in  std_logic_vector(1 downto 0);
        crc_en  : in  std_logic;
        crc_out : out std_logic_vector(31 downto 0)
    );
end entity crc_32;

architecture rtl of crc_32 is

    signal lfsr_q : std_logic_vector(31 downto 0);
    signal lfsr_c : std_logic_vector(31 downto 0);

begin


    -- Parallel 2-bit CRC-32 equations (poly = 0xEDB88320)
    lfsr_c(0)  <= lfsr_q(2);
    lfsr_c(1)  <= lfsr_q(3);
    lfsr_c(2)  <= lfsr_q(4);
    lfsr_c(3)  <= lfsr_q(5);
    lfsr_c(4)  <= data_in(0) xor lfsr_q(0) xor lfsr_q(6);
    lfsr_c(5)  <= data_in(1) xor lfsr_q(1) xor lfsr_q(7);
    lfsr_c(6)  <= lfsr_q(8);
    lfsr_c(7)  <= data_in(0) xor lfsr_q(0) xor lfsr_q(9);
    lfsr_c(8)  <= data_in(0) xor data_in(1) xor lfsr_q(0) xor lfsr_q(1) xor lfsr_q(10);
    lfsr_c(9)  <= data_in(1) xor lfsr_q(1) xor lfsr_q(11);
    lfsr_c(10) <= lfsr_q(12);
    lfsr_c(11) <= lfsr_q(13);
    lfsr_c(12) <= lfsr_q(14);
    lfsr_c(13) <= lfsr_q(15);
    lfsr_c(14) <= data_in(0) xor lfsr_q(0) xor lfsr_q(16);
    lfsr_c(15) <= data_in(1) xor lfsr_q(1) xor lfsr_q(17);
    lfsr_c(16) <= lfsr_q(18);
    lfsr_c(17) <= lfsr_q(19);
    lfsr_c(18) <= data_in(0) xor lfsr_q(0) xor lfsr_q(20);
    lfsr_c(19) <= data_in(0) xor data_in(1) xor lfsr_q(0) xor lfsr_q(1) xor lfsr_q(21);
    lfsr_c(20) <= data_in(0) xor data_in(1) xor lfsr_q(0) xor lfsr_q(1) xor lfsr_q(22);
    lfsr_c(21) <= data_in(1) xor lfsr_q(1) xor lfsr_q(23);
    lfsr_c(22) <= data_in(0) xor lfsr_q(0) xor lfsr_q(24);
    lfsr_c(23) <= data_in(0) xor data_in(1) xor lfsr_q(0) xor lfsr_q(1) xor lfsr_q(25);
    lfsr_c(24) <= data_in(1) xor lfsr_q(1) xor lfsr_q(26);
    lfsr_c(25) <= data_in(0) xor lfsr_q(0) xor lfsr_q(27);
    lfsr_c(26) <= data_in(0) xor data_in(1) xor lfsr_q(0) xor lfsr_q(1) xor lfsr_q(28);
    lfsr_c(27) <= data_in(1) xor lfsr_q(1) xor lfsr_q(29);
    lfsr_c(28) <= data_in(0) xor lfsr_q(0) xor lfsr_q(30);
    lfsr_c(29) <= data_in(0) xor data_in(1) xor lfsr_q(0) xor lfsr_q(1) xor lfsr_q(31);
    lfsr_c(30) <= data_in(0) xor data_in(1) xor lfsr_q(0) xor lfsr_q(1);
    lfsr_c(31) <= data_in(1) xor lfsr_q(1);

    process (clk, reset_n)
    begin
        if reset_n = '0' then
            lfsr_q <= (others => '1');
        elsif rising_edge(clk) then
            if crc_en = '1' then
                lfsr_q <= lfsr_c;
            end if;
        end if;
    end process;

    
    -- Output is the combinatorial next state with final XOR applied
    crc_out <= lfsr_c xor x"FFFFFFFF";

end architecture rtl;
