#set UnusedPin
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullnone [current_design]

create_clock -period 13.888 -name Cam_PCLK [get_ports Cam_PCLK]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets Cam_PCLK_IBUF]

## OV5640
set_property IOSTANDARD LVCMOS33 [get_ports {Cam_Data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cam_Data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cam_Data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cam_Data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cam_Data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cam_Data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cam_Data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Cam_Data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports Cam_Href]
set_property IOSTANDARD LVCMOS33 [get_ports Cam_PCLK]
set_property IOSTANDARD LVCMOS33 [get_ports Cam_Vsync]
set_property IOSTANDARD LVCMOS33 [get_ports XCLK]
set_property IOSTANDARD LVCMOS33 [get_ports cam_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports cam_sda_io]
set_property PACKAGE_PIN C3 [get_ports cam_scl_io]
set_property PACKAGE_PIN D3 [get_ports cam_sda_io]
set_property PULLUP true [get_ports cam_scl_io]
set_property PULLUP true [get_ports cam_sda_io]
set_property PACKAGE_PIN D2 [get_ports Cam_Vsync]
set_property PACKAGE_PIN E2 [get_ports Cam_Href]
set_property PACKAGE_PIN B3 [get_ports Cam_PCLK]
set_property PACKAGE_PIN F7 [get_ports XCLK]
set_property PACKAGE_PIN F4 [get_ports {Cam_Data[7]}]
set_property PACKAGE_PIN H3 [get_ports {Cam_Data[6]}]
set_property PACKAGE_PIN G4 [get_ports {Cam_Data[5]}]
set_property PACKAGE_PIN H4 [get_ports {Cam_Data[4]}]
set_property PACKAGE_PIN C5 [get_ports {Cam_Data[3]}]
set_property PACKAGE_PIN C6 [get_ports {Cam_Data[2]}]
set_property PACKAGE_PIN E7 [get_ports {Cam_Data[1]}]
set_property PACKAGE_PIN B4 [get_ports {Cam_Data[0]}]


## LCD
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_de]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_hs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_vs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_bl]
set_property PACKAGE_PIN M4 [get_ports {lcd_data[15]}]
set_property PACKAGE_PIN K5 [get_ports {lcd_data[14]}]
set_property PACKAGE_PIN J5 [get_ports {lcd_data[13]}]
set_property PACKAGE_PIN K3 [get_ports {lcd_data[12]}]
set_property PACKAGE_PIN K4 [get_ports {lcd_data[11]}]
set_property PACKAGE_PIN H8 [get_ports {lcd_data[10]}]
set_property PACKAGE_PIN L4 [get_ports {lcd_data[9]}]
set_property PACKAGE_PIN R8 [get_ports {lcd_data[8]}]
set_property PACKAGE_PIN J6 [get_ports {lcd_data[7]}]
set_property PACKAGE_PIN J7 [get_ports {lcd_data[6]}]
set_property PACKAGE_PIN M3 [get_ports {lcd_data[5]}]
set_property PACKAGE_PIN M2 [get_ports {lcd_data[4]}]
set_property PACKAGE_PIN L1 [get_ports {lcd_data[3]}]
set_property PACKAGE_PIN L2 [get_ports {lcd_data[2]}]
set_property PACKAGE_PIN J1 [get_ports {lcd_data[1]}]
set_property PACKAGE_PIN J2 [get_ports {lcd_data[0]}]
set_property PACKAGE_PIN P5 [get_ports lcd_bl]
set_property PACKAGE_PIN P6 [get_ports lcd_de]
set_property PACKAGE_PIN N1 [get_ports lcd_hs]
set_property PACKAGE_PIN P1 [get_ports lcd_vs]
set_property PACKAGE_PIN M1 [get_ports lcd_pclk]


## Audio
set_property IOSTANDARD LVCMOS33 [get_ports MCLK]
set_property IOSTANDARD LVCMOS33 [get_ports ADCDAT]
set_property IOSTANDARD LVCMOS33 [get_ports ADCLRC]
set_property IOSTANDARD LVCMOS33 [get_ports BCLK]
set_property IOSTANDARD LVCMOS33 [get_ports DACDAT]
set_property IOSTANDARD LVCMOS33 [get_ports DACLRC]
set_property PACKAGE_PIN N3 [get_ports MCLK]
set_property PACKAGE_PIN P3 [get_ports BCLK]
set_property PACKAGE_PIN M6 [get_ports DACLRC]
set_property PACKAGE_PIN P2 [get_ports DACDAT]
set_property PACKAGE_PIN L6 [get_ports ADCLRC]
set_property PACKAGE_PIN N4 [get_ports ADCDAT]


## GPIO
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[3]}]
set_property PACKAGE_PIN P7 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN R4 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN U2 [get_ports {GPIO_0_0_tri_io[2]}]
set_property PACKAGE_PIN U1 [get_ports {GPIO_0_0_tri_io[3]}]
set_property PULLUP true [get_ports {GPIO_0_0_tri_io[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports Beep]
set_property PACKAGE_PIN R2 [get_ports Beep]

## Eth
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_rd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_rd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_rd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_rd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_td[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_td[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_td[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_td[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_rx_ctrl]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports MDIO_PHY_0_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports MDIO_PHY_0_mdio_io]

set_property PACKAGE_PIN Y12 [get_ports {RGMII_rd[3]}]
set_property PACKAGE_PIN Y13 [get_ports {RGMII_rd[2]}]
set_property PACKAGE_PIN W12 [get_ports {RGMII_rd[1]}]
set_property PACKAGE_PIN W13 [get_ports {RGMII_rd[0]}]
set_property PACKAGE_PIN U13 [get_ports {RGMII_td[3]}]
set_property PACKAGE_PIN U14 [get_ports {RGMII_td[2]}]
set_property PACKAGE_PIN T16 [get_ports {RGMII_td[1]}]
set_property PACKAGE_PIN U16 [get_ports {RGMII_td[0]}]
set_property PACKAGE_PIN U18 [get_ports RGMII_tx_clk]
set_property PACKAGE_PIN Y14 [get_ports RGMII_rx_clk]
set_property PACKAGE_PIN Y15 [get_ports RGMII_rx_ctrl]
set_property PACKAGE_PIN U17 [get_ports RGMII_tx_ctl]
set_property PACKAGE_PIN U11 [get_ports MDIO_PHY_mdc]
set_property PACKAGE_PIN U12 [get_ports MDIO_PHY_mdio_io]

## IIC1
set_property IOSTANDARD LVCMOS33 [get_ports IIC1_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC1_sda_io]
set_property PULLUP true [get_ports IIC1_sda_io]
set_property PULLUP true [get_ports IIC1_scl_io]
set_property PACKAGE_PIN J3 [get_ports IIC1_scl_io]
set_property PACKAGE_PIN K2 [get_ports IIC1_sda_io]


set_property PACKAGE_PIN T2 [get_ports tmds_clk_p_0]
set_property IOSTANDARD TMDS_33 [get_ports tmds_clk_p_0]
set_property IOSTANDARD TMDS_33 [get_ports tmds_clk_n_0]

## GPIO0 (unchanged 36-bit bus)
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[35]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[34]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[33]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_0_tri_io[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_p_0[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_n_0[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_p_0[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_n_0[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_p_0[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_n_0[0]}]
set_property PACKAGE_PIN N6 [get_ports {tmds_data_p_0[0]}]
set_property PACKAGE_PIN M8 [get_ports {tmds_data_p_0[1]}]
set_property PACKAGE_PIN K7 [get_ports {tmds_data_p_0[2]}]
set_property PACKAGE_PIN B7 [get_ports {GPIO0_0_tri_io[0]}]
set_property PACKAGE_PIN B6 [get_ports {GPIO0_0_tri_io[1]}]
set_property PACKAGE_PIN D5 [get_ports {GPIO0_0_tri_io[2]}]
set_property PACKAGE_PIN C4 [get_ports {GPIO0_0_tri_io[3]}]
set_property PACKAGE_PIN G8 [get_ports {GPIO0_0_tri_io[4]}]
set_property PACKAGE_PIN G7 [get_ports {GPIO0_0_tri_io[5]}]
set_property PACKAGE_PIN C8 [get_ports {GPIO0_0_tri_io[6]}]
set_property PACKAGE_PIN B8 [get_ports {GPIO0_0_tri_io[7]}]
set_property PACKAGE_PIN H5 [get_ports {GPIO0_0_tri_io[8]}]
set_property PACKAGE_PIN H6 [get_ports {GPIO0_0_tri_io[9]}]
set_property PACKAGE_PIN G6 [get_ports {GPIO0_0_tri_io[10]}]
set_property PACKAGE_PIN F6 [get_ports {GPIO0_0_tri_io[11]}]
set_property PACKAGE_PIN H1 [get_ports {GPIO0_0_tri_io[12]}]
set_property PACKAGE_PIN G1 [get_ports {GPIO0_0_tri_io[13]}]
set_property PACKAGE_PIN G3 [get_ports {GPIO0_0_tri_io[14]}]
set_property PACKAGE_PIN G2 [get_ports {GPIO0_0_tri_io[15]}]
set_property PACKAGE_PIN F2 [get_ports {GPIO0_0_tri_io[16]}]
set_property PACKAGE_PIN F1 [get_ports {GPIO0_0_tri_io[17]}]
set_property PACKAGE_PIN E4 [get_ports {GPIO0_0_tri_io[18]}]
set_property PACKAGE_PIN E3 [get_ports {GPIO0_0_tri_io[19]}]
set_property PACKAGE_PIN D1 [get_ports {GPIO0_0_tri_io[20]}]
set_property PACKAGE_PIN C1 [get_ports {GPIO0_0_tri_io[21]}]
set_property PACKAGE_PIN F5 [get_ports {GPIO0_0_tri_io[22]}]
set_property PACKAGE_PIN E5 [get_ports {GPIO0_0_tri_io[23]}]
set_property PACKAGE_PIN B2 [get_ports {GPIO0_0_tri_io[24]}]
set_property PACKAGE_PIN B1 [get_ports {GPIO0_0_tri_io[25]}]
set_property PACKAGE_PIN D7 [get_ports {GPIO0_0_tri_io[26]}]
set_property PACKAGE_PIN D6 [get_ports {GPIO0_0_tri_io[27]}]
set_property PACKAGE_PIN A2 [get_ports {GPIO0_0_tri_io[28]}]
set_property PACKAGE_PIN A1 [get_ports {GPIO0_0_tri_io[29]}]
set_property PACKAGE_PIN E8 [get_ports {GPIO0_0_tri_io[30]}]
set_property PACKAGE_PIN D8 [get_ports {GPIO0_0_tri_io[31]}]
set_property PACKAGE_PIN A5 [get_ports {GPIO0_0_tri_io[32]}]
set_property PACKAGE_PIN A4 [get_ports {GPIO0_0_tri_io[33]}]
set_property PACKAGE_PIN A7 [get_ports {GPIO0_0_tri_io[34]}]
set_property PACKAGE_PIN A6 [get_ports {GPIO0_0_tri_io[35]}]

## GPIO1 header  (renamed from GPIO1_0_tri_io[0..35])
## SW/LED/KEY grouped as buses; control signals kept as named scalars.
## VERIFIED: LED[0]=AB14 (matches original "// LED 0" comment).
## INFERRED: UART/ADC/DAC signal-to-pin pairing (bits 26..35) - pins are
## certain, pairing extrapolated from the silkscreen layout. Verify SPI.
##############################################################################

## --- Switches SW[7:0] (input) ---
set_property PACKAGE_PIN AB22 [get_ports {SW[0]}]
set_property PACKAGE_PIN AB21 [get_ports {SW[1]}]
set_property PACKAGE_PIN AA20 [get_ports {SW[2]}]
set_property PACKAGE_PIN AA19 [get_ports {SW[3]}]
set_property PACKAGE_PIN AB19 [get_ports {SW[4]}]
set_property PACKAGE_PIN AB18 [get_ports {SW[5]}]
set_property PACKAGE_PIN Y19  [get_ports {SW[6]}]
set_property PACKAGE_PIN Y18  [get_ports {SW[7]}]

## --- LEDs LED[7:0] (output) ---
set_property PACKAGE_PIN AB14 [get_ports {LED[0]}]
set_property PACKAGE_PIN AA14 [get_ports {LED[1]}]
set_property PACKAGE_PIN AA15 [get_ports {LED[2]}]
set_property PACKAGE_PIN AA12 [get_ports {LED[3]}]
set_property PACKAGE_PIN R17  [get_ports {LED[4]}]
set_property PACKAGE_PIN T17  [get_ports {LED[5]}]
set_property PACKAGE_PIN U19  [get_ports {LED[6]}]
set_property PACKAGE_PIN V19  [get_ports {LED[7]}]

## --- Keys KEY[4:0] (input) ---
set_property PACKAGE_PIN AB12 [get_ports {KEY[0]}]
set_property PACKAGE_PIN V11  [get_ports {KEY[1]}]
set_property PACKAGE_PIN W11  [get_ports {KEY[2]}]
set_property PACKAGE_PIN AA11 [get_ports {KEY[3]}]
set_property PACKAGE_PIN AB11 [get_ports {KEY[4]}]

## --- 7-segment 74HC595 control (scalars) ---
set_property PACKAGE_PIN AA16 [get_ports DIO]   ;# serial data
set_property PACKAGE_PIN AA17 [get_ports RCLK]  ;# latch
set_property PACKAGE_PIN AB13 [get_ports SCLK]  ;# shift clock

## --- Unlabeled pair on silkscreen (scalars, kept generic) ---
set_property PACKAGE_PIN AB16 [get_ports GPIO1_08]
set_property PACKAGE_PIN AB17 [get_ports GPIO1_09]

## --- UART / IR (scalars, INFERRED pairing) ---
set_property PACKAGE_PIN V18  [get_ports TXD]
set_property PACKAGE_PIN W18  [get_ports RXD]
set_property PACKAGE_PIN W17  [get_ports IR]

## --- ADC (scalars, INFERRED pairing) ---
set_property PACKAGE_PIN Y17  [get_ports ADC_SCLK]
set_property PACKAGE_PIN V16  [get_ports ADC_SDAT]
set_property PACKAGE_PIN W16  [get_ports ADC_SADDR]
set_property PACKAGE_PIN V15  [get_ports ADC_CS_N]

## --- DAC (scalars, INFERRED pairing) ---
set_property PACKAGE_PIN W15  [get_ports DAC_DIN]
set_property PACKAGE_PIN V13  [get_ports DAC_SCLK]
set_property PACKAGE_PIN V14  [get_ports DAC_CS_N]

## --- IOSTANDARD ---
set_property IOSTANDARD LVCMOS33 [get_ports {SW[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {KEY[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIO RCLK SCLK}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO1_08 GPIO1_09}]
set_property IOSTANDARD LVCMOS33 [get_ports {TXD RXD IR}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCLK ADC_SDAT ADC_SADDR ADC_CS_N}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_DIN DAC_SCLK DAC_CS_N}]

##############################################################################
##############################################################################

set_property IOSTANDARD TMDS_33 [get_ports tmds_clk_0_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_0_v_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_0_v_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_0_v_p[0]}]
set_property PACKAGE_PIN K7 [get_ports {tmds_data_0_v_p[2]}]
set_property PACKAGE_PIN M8 [get_ports {tmds_data_0_v_p[1]}]
set_property PACKAGE_PIN N6 [get_ports {tmds_data_0_v_p[0]}]
set_property PACKAGE_PIN T2 [get_ports tmds_clk_0_clk_p]

set_property PACKAGE_PIN L5 [get_ports clk_in50M]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in50M]

set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[4]}]
set_property PACKAGE_PIN R7 [get_ports {GPIO_0_0_tri_io[4]}]