SIM ?= ghdl
TOPLEVEL_LANG = vhdl
VHDL_SOURCES_unisim = ../../bringup.srcs/sim_1/imports/new/iddr_model.vhd
VHDL_SOURCES = ../../bringup.srcs/sources_1/new/gigabit_rx.vhd

TOPLEVEL = gigabit_rx
MODULE = gigabit_rx_tb
EXTRA_ARGS += --std=08


include $(shell cocotb-config --makefiles)/Makefile.sim